language: php

matrix:
  include:
    - php: 7.1
      env:
        - TEST_COVERAGE=true
    - php: 7.2
    - php: 7.3

install:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev satooshi/php-coveralls ; fi

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - composer validate
  - ./vendor/bin/phpcs --standard=PSR2 src tests
  - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $TEST_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/php-coveralls -v ; fi
